# NumPy

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' ,'5' ]
array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

Yes, there is a difference between the data types of list_ and array_list.

list_ is a Python list, which is a versatile data structure that can hold elements of different data types. 
array_list is a NumPy array, which is optimized for numerical operations and typically holds elements of the same data type.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))  # Output: <class 'list'>
print(type(array_list))  # Output: <class 'numpy.ndarray'>


<class 'list'>
<class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.**

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
array_list = np.array(object = list_, dtype = int)


**Q3. Considering the following changes in the variable, array_list stated above, Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.**

Yes, there will be a difference in the data type of the elements.   

- list_ will still contain elements of type str.
- array_list will contain elements of type int due to the dtype=int argument in np.array.

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))
##This code will demonstrate the change in data types after converting the list to a NumPy array with dtype=int.


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [2]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

**Q4. Write a code to find the following characteristics of variable, num_array:**
**(i) shape**
**(ii) size**

In [3]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# (i) Shape of the array
print("Shape of the array:", num_array.shape)

# (ii) Size of the array
print("Size of the array:", num_array.size)


Shape of the array: (2, 3)
Size of the array: 6


**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.**

In [4]:
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

In [5]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
